# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: def1bcfbb8f7888dd9c9536c1dbc5837a53d638cde9a36ba737515f30c8c8868497652ee9e1b7d6595fb3e318caaa8f611a8e7553f70a7c77e53f9ce2c0dbc4a

test:
  secret_key_base: b9a1844a5d7707764e8855647038c9be851ab8ff3056b4b6c49ebdd0f4a5d641e7f46f69ebf8995d3bac47549dc9cfc18f8b149a8f916aa6d9ff3f751d4e3445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
